version: "3.8"
services:
  flaskapp :
    build: ./flaskapp/
    container_name: flaskapp
    restart: always
    environment:
      - DBHOST=postgres
      - DBUSERNAME=username
      - DBPASSWORD=secret
      - DBPORT=5432
      - DATABASE=database
      - APP_NAME=FlaskApp
    ports:
      - 5000:5000
    depends_on: 
      - db
  app :
    build: ./app/
    container_name: app
    environment:
      - DBHOST=postgres
      - DBUSERNAME=username
      - DBPASSWORD=secret
      - DBPORT=5432
      - DATABASE=database
    depends_on: 
      - db
  db:
    build: ./database/
    container_name: postgres
  nginx:
    build: ./nginx/
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - flaskapp
